### ISSUE TITLE
Dockerについて触れてみる

### ISSUE THREAD

**Issue by yuyuue** [yuyuue/KnowledgeBase#62]
コンテナを扱うためのツール？ソフト？みたいなイメージ。

**Comment by yuyuue** [comment]
公式からダウンロード
https://docs.docker.com/get-started/get-docker/

**Comment by yuyuue** [comment]
インストール完了したのでdocker.desctopのWalkthroughsを進める。

**Comment by yuyuue** [comment]
チュートリアル4つ終わるまでメモ書き忘れてた。。。

## 単純なコンテナ
- DockerfileというファイルがDockerの設定ファイル。
- ```docker build -t welcome-to-docker .```で起動できる。
-tはイメージ名を決めるパラメータ。
末尾の.はDockerfileを探すディレクトリパス。

## マルチコンテナ
- yamlファイルにコンテナごとの設定を記載する。
- ```docker compose up -d```でマルチコンテナアプリを起動する。

**Comment by yuyuue** [comment]
## データの永続性
- compose.yaml内のvolumesという設定を使ってローカルのファイルシステムにマウントさせる。

**Comment by yuyuue** [comment]
## ローカルのファイルとの同期
- これもcompose.yaml内でvolumesを使う。（./app:/usr/src/app）
- モジュールが入ってるフォルダは同期しない、みたいな設定もできるっぽい。（/usr/src/app/node_modules）
```yaml
services:
  todo-app:
    build:
      context: ./app
    links:
      - todo-database
    volumes: 
     - ./app:/usr/src/app
     - /usr/src/app/node_modules
    ports:
      - 3001:3001

  todo-database:
    image: mongo:6
    command: mongod --port 27018
    ports:
      - 27018:27018
```
