### ISSUE TITLE
【Docker】Pythonでどのようにコンテナを扱うかを確認する

### ISSUE THREAD

**Issue by yuyuue** [yuyuue/KnowledgeBase#70]
#62 で基本操作チュートリアルはできたので、コンテナを作ってみる。

**Comment by yuyuue** [comment]
以下のPython用ガイドを参考にする
https://docs.docker.com/guides/python/

**Comment by yuyuue** [comment]
まずはチュートリアルのサンプルアプリを立ち上げた。
内容はチュートリアルの手順1まんまなのでザックリ書くと、
```docker init```で適切に回答すればdockerfileとcompose.yamlが作られるのでそれを基に`docker compose up --build`すればいい。

**Comment by yuyuue** [comment]
`docker compose up --build`で以下エラーが発生したので`requirements.txt`のpsycopgおよびpsycopg-binaryのバージョンを3.2.1から3.2.5に変更した。
`Could not find a version that satisfies the requirement psycopg-binary==3.2.1 (from versions: 3.2.2, 3.2.3, 3.2.4, 3.2.5)`

とりあえずbuildは通った。

**Comment by yuyuue** [comment]
通ったけどエラーが発生してるので原因調査→解消する。

**Comment by yuyuue** [comment]
compose.yamlのdb設定、PASSWORD_FLIEパスがdb-passworになっていた
`Value error, Password file /run/secrets/db-passwor does not exist. [type=value_error, input_value='/run/secrets/db-passwor', input_type=str]`

**Comment by yuyuue** [comment]
同様のエラー発生。
`Value error, Password file /run/secrets/db-password does not exist. [type=value_error, input_value='/run/secrets/db-password', input_type=s`

チュートリアルだとパスワードは以下の対応だけしろって書いてたけど他にも必要なのか？
> Before you run the application using Compose, notice that this Compose file specifies a password.txt file to hold the database's password. You must create this file as it's not included in the source repository.
In the cloned repository's directory, create a new directory named db and inside that directory create a file named password.txt that contains the password for the database. Using your favorite IDE or text editor, add the following contents to the password.txt file.

**Comment by yuyuue** [comment]
以下の記載がされているのでファイルの配置自体は問題なさそう。
```yaml
secrets:
  db-password:
    file: db/password.txt
```

[参考：日本語化リファレンス](https://docs.docker.jp/compose/compose-file/compose-file-v3.html#secrets)

**Comment by yuyuue** [comment]
奇妙なのは、データベースのサーバーの方は同じパスで問題なく起動できていること。

**Comment by yuyuue** [comment]
チュートリアルに記載のcompose.yamlをすべて張り付けると問題無く動作した。
どこが問題なのか分からないので比較する。

**Comment by yuyuue** [comment]
サーバー側のsecretsが抜けていた。（添付の末尾）
compose.yamlの書き方として、secretsでシークレット情報をまとめて書いておき、そのどれを使うかを各サーバーで指定する必要があるっぽい。

```yaml
services:
  server:
    build:
      context: .
    ports:
      - 8001:8001
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
```

**Comment by yuyuue** [comment]
チュートリアルのコマンドをcmdで打ってもうまくいかなかった。
→Git Bash使って打てばうまくいった。
```bash
$ curl -X 'POST' \
> 'http://localhost:8001/heroes/' \
> -H 'accept: application/json' \
> -H 'Content-Type: application/json' \
> -d '{
> "id": 1,
>   "name": "my hero",
  "secret_name": "austing",
  "age": 12
}'
{"age":12,"secret_name":"austing","name":"my hero","id":1}
```

**Comment by yuyuue** [comment]
getリクエストでしっかり登録済みのデータを返す。
bash
```bash
$ curl -X 'GET' \
  'http://localhost:8001/heroes/' \
  -H 'accept: application/json'
[{"age":12,"secret_name":"austing","name":"my hero","id":1}]
```

code
```Python
@app.get("/heroes/")
def read_heroes():
    with Session(engine) as session:
        heroes = session.exec(select(Hero)).all()
        return heroes
```

**Comment by yuyuue** [comment]
ファイルに更新があった場合に自動的にコンテナへ反映させるための設定。
server直下にdevelopセクションを作ってその下にwatchセクションを作る。
コマンド`docker compose watch`で起動。

```yaml
    develop:
      watch:
        - action: rebuild
          path: .
```

### 公式ref: develop
- https://docs.docker.com/reference/compose-file/services/#develop
- https://docs.docker.com/reference/compose-file/develop/
